default:
  # api_gwasinfo
  # Endpoint to fetch gwas info
  # TODO: Update url when api is released
  api_gwasinfo: http://apitest.mrbase.org/gwasinfo/
  # refdata:
  # Reference dataset to calculate allele frequency.
  refdata: ref_data/1kg_v3_nomult.bcf
  # meta_report_dir:
  # Name of the (sub)directory to store meta results
  meta_report_dir: meta
