name: mrbase-report
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2018.11.29
  - openssl=1.0.2p
  - r-flexdashboard=0.5.1.1
  - r-fs=1.2.6
  - r-here=0.1
  - r-htmlwidgets=1.2
  - r-httpuv=1.4.5
  - r-later=0.7.3
  - r-promises=1.0.1
  - r-shiny=1.2.0
  - r-sourcetools=0.1.7
  - r-xtable=1.8_3
  - bwidget=1.9.11
  - bzip2=1.0.6
  - cairo=1.14.12
  - cctools=895
  - clang=4.0.1
  - clang_osx-64=4.0.1
  - clangxx=4.0.1
  - clangxx_osx-64=4.0.1
  - compiler-rt=4.0.1
  - curl=7.61.1
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gettext=0.19.8.1
  - gfortran_osx-64=4.8.5
  - glib=2.56.2
  - graphite2=1.3.12
  - gsl=2.4
  - harfbuzz=1.8.8
  - icu=58.2
  - jpeg=9b
  - krb5=1.16.1
  - ld64=274.2
  - libcurl=7.61.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libopenblas=0.3.3
  - libpng=1.6.35
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libxml2=2.9.8
  - llvm=4.0.1
  - llvm-lto-tapi=4.0.1
  - llvm-openmp=4.0.1
  - make=4.2.1
  - ncurses=6.1
  - pango=1.42.4
  - pcre=8.42
  - pixman=0.34.0
  - readline=7.0
  - tk=8.6.8
  - tktable=2.10
  - xz=5.2.4
  - zlib=1.2.11
  - _r-mutex=1.0.0
  - r-argparse=1.1.1
  - r-assertthat=0.2.0
  - r-backports=1.1.2
  - r-base=3.5.1
  - r-base64enc=0.1_3
  - r-bh=1.66.0_1
  - r-bindr=0.1.1
  - r-bindrcpp=0.2.2
  - r-broom=0.5.0
  - r-callr=2.0.4
  - r-cellranger=1.1.0
  - r-cli=1.0.0
  - r-clipr=0.4.1
  - r-colorspace=1.3_2
  - r-crayon=1.3.4
  - r-curl=3.2
  - r-dbi=1.0.0
  - r-dbplyr=1.2.2
  - r-dichromat=2.0_0
  - r-digest=0.6.15
  - r-dplyr=0.7.6
  - r-evaluate=0.11
  - r-fansi=0.2.3
  - r-findpython=1.0.3
  - r-forcats=0.3.0
  - r-getopt=1.20.2
  - r-ggplot2=3.0.0
  - r-glue=1.3.0
  - r-gtable=0.2.0
  - r-haven=1.1.2
  - r-highr=0.7
  - r-hms=0.4.2
  - r-htmltools=0.3.6
  - r-httr=1.3.1
  - r-jsonlite=1.5
  - r-knitr=1.20
  - r-labeling=0.3
  - r-lattice=0.20_35
  - r-lazyeval=0.2.1
  - r-lubridate=1.7.4
  - r-magrittr=1.5
  - r-markdown=0.8
  - r-mass=7.3_50
  - r-matrix=1.2_14
  - r-mgcv=1.8_24
  - r-mime=0.5
  - r-modelr=0.1.2
  - r-munsell=0.5.0
  - r-nlme=3.1_137
  - r-openssl=1.0.2
  - r-pillar=1.3.0
  - r-pkgconfig=2.0.1
  - r-plogr=0.2.0
  - r-plyr=1.8.4
  - r-praise=1.0.0
  - r-processx=3.1.0
  - r-proto=1.0.0
  - r-purrr=0.2.5
  - r-r6=2.2.2
  - r-rcolorbrewer=1.1_2
  - r-rcpp=0.12.18
  - r-readr=1.1.1
  - r-readxl=1.1.0
  - r-rematch=1.0.1
  - r-reprex=0.2.0
  - r-reshape2=1.4.3
  - r-rlang=0.2.1
  - r-rmarkdown=1.10
  - r-rprojroot=1.3_2
  - r-rstudioapi=0.7
  - r-rvest=0.3.2
  - r-scales=0.5.0
  - r-selectr=0.4_1
  - r-stringi=1.2.4
  - r-stringr=1.3.1
  - r-testthat=2.0.0
  - r-tibble=1.4.2
  - r-tidyr=0.8.1
  - r-tidyselect=0.2.4
  - r-tidyverse=1.2.1
  - r-tinytex=0.6
  - r-utf8=1.1.4
  - r-viridislite=0.3.0
  - r-whisker=0.3_2
  - r-withr=2.1.2
  - r-xfun=0.3
  - r-xml2=1.2.0
  - r-yaml=2.2.0
