---
title: "Pipeline report"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library("flexdashboard")
library("tidyverse")
library("vcfR")
library("jsonlite")
source("funcs/plots.R")
```

```{shell, include=FALSE}
bcftools query -f '%CHROM\t%POS\t%ID\t%INFO/PVAL\n' data/harmonised.bcf > data/harmonised_query.tsv
```

```{r, include=FALSE}
df <- read_tsv("data/harmonised_query.tsv", col_names = FALSE,
               col_types = "cicd") %>%
  set_names(c("CHROM", "POS", "ID", "PVAL")) %>%
  mutate(CHROM = if_else(CHROM == "X", 23L, if_else(CHROM == "Y", 24L, as.integer(CHROM))))
```

Column {data-width=450, .sidebar}
-----------------------------------------------------------------------

### Information {data-height=200}

```{r}
info <- tribble(
  ~name, ~value,
  "input_file1", "PLACEHOLDER",
  "input_file2", "PLACEHOLDER",
  "compile_time", format(Sys.time(), "%Y-%m-%d %H:%M"),
  "build_version", "PLACEHOLDER",
)

info %>% knitr::kable()
```

### Metrics

```{r}
meta_metrics <- "data/harmonised.json" %>% read_json()

count_metrics <- meta_metrics$counts

count_metrics %>% enframe() %>%
  mutate(value = value %>%
           map_int( ~ .)) %>% knitr::kable(format.args = list(big.mark = ","))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Plot 1: Manhattan plot

```{r}
df %>% plot_manhattan(chr = CHROM, bp = POS, snp = ID, p = PVAL)
```

Column {.tabset .tabset-fade}
-----------------------------------------------------------------------


### Plot 2: QQ plot

```{r}
df %>% plot_qq(pval = PVAL)
```

### Plot 3: placeholder

```{r}

```
