name: ieu-gwas-report
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - r-base=4.0.3
  - r-tidyverse
  - r-data.table
  - r-devtools
  - r-rlang>=0.3
  - r-markdown
  - r-flexdashboard
  - r-config
  - r-here
  - r-logging
  - r-glue
  - r-fs
  - r-skimr
  - r-argparse
  - r-styler
  - r-lintr
  - pandoc
  - bcftools=1.9
  - plink=1.90b4
