name: mrbase-report
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
dependencies:
  - python=3.6.5
  - r-base=3.5.1
  - r-tidyverse=1.2.1
  - r-data.table
  - r-markdown
  - r-here
  - r-logging
  - r-glue
  - r-fs
  - r-highcharter
  - r-argparse=2.0.1
  - pandoc
  - bcftools=1.9
  - plink=1.90b4
